### ISSUE TITLE
Reference to non-existing directory

### ISSUE THREAD

**Issue by Achllle** [osrf/rmf-web#224]
When I run `npm run bootstrap`, I get:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /~/rmf-web/packages/dashboard/node_modules/ros2-bridge/src/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/~/rmf-web/packages/dashboard/node_modules/ros2-bridge/src/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
however the folder `node_modules` doesn't seem to exist

**Comment by koonpeng** [comment]
You need to give more context on what you are doing,

which package does it fail on?
were there any other errors from npm?
were you able to build the typescript files?
are you running as root?

**Comment by Achllle** [comment]
Here's the full log. Previous steps did not report errors. I'm running inside a docker container as root. Not sure what you mean by "you need to give more context". I'm simply following the instructions in the main README.
```
> root@ bootstrap /~/rmf-web
> node scripts/bootstrap.js


> husky@4.3.0 install /~/rmf-web/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> core-js@3.6.5 postinstall /~/rmf-web/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[...]
> core-js-pure@3.6.5 postinstall /~/rmf-web/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

[...]

> husky@4.3.0 postinstall /~/rmf-web/node_modules/husky
> opencollective-postinstall || exit 0

[...]

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[...]

> int64-napi@1.0.1 install /~/rmf-web/packages/ros2-bridge/node_modules/int64-napi
> node-gyp rebuild

make: Entering directory '/~/rmf-web/packages/ros2-bridge/node_modules/int64-napi/build'
  CC(target) Release/obj.target/int64/src/int64.o
  SOLINK_MODULE(target) Release/obj.target/int64.node
  COPY Release/int64.node
make: Leaving directory '/~/rmf-web/packages/ros2-bridge/node_modules/int64-napi/build'

> ref-napi@3.0.1 install /~/rmf-web/packages/ros2-bridge/node_modules/ref-napi
> node-gyp-build


> rclnodejs@0.17.0 install /~/rmf-web/packages/ros2-bridge/node_modules/rclnodejs
> node-gyp rebuild

make: Entering directory '/~/rmf-web/packages/ros2-bridge/node_modules/rclnodejs/build'
  CXX(target) Release/obj.target/rclnodejs/src/addon.o
In file included from ../../nan/nan.h:56,
                 from ../src/addon.cpp:15:
/root/.cache/node-gyp/12.20.1/include/node/node.h:737:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  737 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/12.20.1/include/node/node.h:771:3: note: in expansion of macro ‘NODE_MODULE_X’
  771 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/addon.cpp:94:1: note: in expansion of macro ‘NODE_MODULE’
   94 | NODE_MODULE(rclnodejs, InitModule);
      | ^~~~~~~~~~~
  CXX(target) Release/obj.target/rclnodejs/src/executor.o
  CXX(target) Release/obj.target/rclnodejs/src/handle_manager.o
  CXX(target) Release/obj.target/rclnodejs/src/rcl_action_bindings.o
  CXX(target) Release/obj.target/rclnodejs/src/rcl_bindings.o
  CXX(target) Release/obj.target/rclnodejs/src/rcl_handle.o
  CXX(target) Release/obj.target/rclnodejs/src/rcl_lifecycle_bindings.o
  CXX(target) Release/obj.target/rclnodejs/src/rcl_utilities.o
  CXX(target) Release/obj.target/rclnodejs/src/shadow_node.o
  SOLINK_MODULE(target) Release/obj.target/rclnodejs.node
  COPY Release/rclnodejs.node
make: Leaving directory '/~/rmf-web/packages/ros2-bridge/node_modules/rclnodejs/build'

> rclnodejs@0.17.0 postinstall /~/rmf-web/packages/ros2-bridge/node_modules/rclnodejs
> node scripts/generate_messages.js

Start JavaScript message generation...
Generation complete.
npm WARN lifecycle ros2-bridge@0.0.1~prepare: cannot run in wd ros2-bridge@0.0.1 npm run build (wd=/~/rmf-web/packages/ros2-bridge)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 681 packages from 474 contributors and audited 682 packages in 18.437s

[...]

> core-js@3.8.3 postinstall /~/rmf-web/packages/react-components/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[...]

> core-js-pure@3.6.5 postinstall /~/rmf-web/packages/react-components/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

[...]

> date-fns@2.0.0-alpha.27 postinstall /~/rmf-web/packages/react-components/node_modules/date-fns
> node ./docs/printV2Notice.js

[...]

npm WARN lifecycle react-components@0.0.1~prepare: cannot run in wd react-components@0.0.1 npm run build (wd=/~/rmf-web/packages/react-components)
npm WARN react-components@0.0.1 requires a peer of @material-ui/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-components@0.0.1 requires a peer of @material-ui/icons@^4.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-components@0.0.1 requires a peer of @material-ui/lab@^4.0.0-alpha.56 but none is installed. You must install peer dependencies yourself.
npm WARN react-components@0.0.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-components@0.0.1 No description
npm WARN react-components@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 986 packages from 586 contributors and audited 988 packages in 8.574s

[...]

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /~/rmf-web/packages/dashboard/node_modules/ros2-bridge/src/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/~/rmf-web/packages/dashboard/node_modules/ros2-bridge/src/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-05T21_30_54_121Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! root@ bootstrap: `node scripts/bootstrap.js`
npm ERR! Exit status 254
npm ERR! 
npm ERR! Failed at the root@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-05T21_30_54_171Z-debug.log
```

I replaced parts that seemed irrelevant with `[...]`.
The 'complete log':
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.nvm/versions/node/v12.20.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v12.20.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose stack Error: missing script: setup
4 verbose stack     at run (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd /~/rmf-web
6 verbose Linux 5.4.0-42-generic
7 verbose argv "/root/.nvm/versions/node/v12.20.1/bin/node" "/root/.nvm/versions/node/v12.20.1/bin/npm" "run" "setup"
8 verbose node v12.20.1
9 verbose npm  v6.14.10
10 error missing script: setup
11 verbose exit [ 1, true ]
```

**Comment by koonpeng** [comment]
Thanks for the extra info.

I don't see the typescript files being compiled, you might need to allow unsafe-perm https://docs.npmjs.com/cli/v6/using-npm/config#unsafe-perm.

Regarding the 2nd log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.nvm/versions/node/v12.20.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v12.20.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose stack Error: missing script: setup
4 verbose stack     at run (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /root/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd /~/rmf-web
6 verbose Linux 5.4.0-42-generic
7 verbose argv "/root/.nvm/versions/node/v12.20.1/bin/node" "/root/.nvm/versions/node/v12.20.1/bin/npm" "run" "setup"
8 verbose node v12.20.1
9 verbose npm  v6.14.10
10 error missing script: setup
11 verbose exit [ 1, true ]
```
It seems like it is running to run the setup script, which should not happen as part of the bootstrap. I'm assuming you are trying to run the setup script in `packages/dashboard`, if so, make sure that you are in the correct working directory.

**Comment by Achllle** [comment]
I set it using `npm config set unsafe-perm true` and that seemed to do it!
After it had failed I had tried to run `npm start` so that's probably what those logs pertain to.

Side note: I had to run source `~/.nvm/nvm.sh` before `nvm install 12` to avoid `nvm not found`.

Thanks for your help. I think this can be closed - not sure if we want to add something to the instructions.
